[package]
name = "specs-test"
version = "0.1.0"
authors = ["Max Hunt <max@huntw3.com>"]
edition = "2018"

[dependencies]
specs = "0.14"
quicksilver = "0.3"

[build-dependencies]
serde = "1.0"
ron = "0.4"
handlebars = "1.1"
